name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy_monorep:
    name: Deploying the monorepo to staging
    runs-on: ubuntu-latest

    steps:
      - name: set up ssh
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 13.49.246.178 >> ~/.ssh/known_hosts
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: deploy staging
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@13.49.246.178 << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
          cd /home/ubuntu/mono-staging/
          npm i -g pnpm
          pnpm install
          pnpm run build
          pm2 restart all
          EOF 