name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy_monorep:
    name: Deploying the monorepo to staging
    runs-on: ubuntu-latest

    steps:
      - name: set up ssh
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 51.21.220.237 >> ~/.ssh/known_hosts
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: deploy staging
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@51.21.220.237
          cd /home/ubuntu/mono-staging
          npm i -g pnpm
          pnpm install
          pnpm run build
          pm2 restart all