name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy_monorep:
    name: Deploying the monorepo to staging
    runs-on: ubuntu-latest

    steps:
      - name: set up ssh
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 51.21.220.237 >> ~/.ssh/known_hosts
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa root@51.21.220.237